# Generated by Django 4.2.4 on 2023-09-06 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Production_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категории предприятий')),
            ],
            options={
                'verbose_name': 'Категория предприятий',
                'verbose_name_plural': 'Категории предприятий',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Загаловок')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('img', models.ImageField(null=True, upload_to='images/', verbose_name='Изображение')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('currency', models.CharField(max_length=250, verbose_name='Валюта')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('contact_person', models.CharField(max_length=250, verbose_name='Контактное лицо')),
                ('number_phone', models.CharField(max_length=250, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.production_categories', verbose_name='Категория')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Наименование предприятия')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('legal_address', models.CharField(max_length=100, verbose_name='Юридический адрес')),
                ('number_phone', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Логотип')),
                ('production_categories', models.ManyToManyField(to='index.production_categories', verbose_name='Категории предприятия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.advert', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
    ]
