# Generated by Django 4.2.4 on 2023-09-09 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Загаловок')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('img', models.ImageField(null=True, upload_to='images/', verbose_name='Изображение')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('currency', models.CharField(max_length=250, verbose_name='Валюта')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('contact_person', models.CharField(max_length=250, verbose_name='Контактное лицо')),
                ('number_phone', models.CharField(max_length=250, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.production_categories', verbose_name='Категория')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
